---
mode: commit
min_length: 3
allowed:
  - acl
  - acls
  - adfs
  - addons
  - apitest
  - apikey
  - apk
  - aspell
  - attrs
  - auth
  - autofill
  - aws
  - axios
  - backend
  - backends
  - backport
  - bmarkovic
  - browserslist
  - bvue
  - caniuse
  - casbin
  - chmigrate
  - cli
  - clickhouse
  - composable
  - conf
  - config
  - const
  - cpu
  - crd
  - cronjob
  - cve
  - cwe
  - dapi
  - dataplane
  - dataplaneapi
  - dataplanes
  - datepicker
  - dereference
  - discoverability
  - durations
  - dns
  - dom
  - dpapi
  - dpapis
  - dropdowns
  - dsn
  - e2e
  - entrypoint
  - enum
  - env
  - eol
  - epoll
  - escaper
  - eslint
  - failsafe
  - fbt
  - formatter
  - formatters
  - frontend
  - frontends
  - fullpage
  - github
  - gitlab
  - gokc
  - golang
  - golangci
  - gorm
  - goroutines
  - govulncheck
  - hapee
  - haproxy
  - healthcheck
  - healthz
  - hostname
  - html
  - http
  - https
  - httpCLF
  - iana
  - ineffassign
  - infos
  - ioutil
  - ipam
  - istanbul
  - jose
  - json
  - jsonpath
  - jwt
  - kasbin
  - kpi
  - kubebuilder
  - kubernetes
  - lifecycle
  - linter
  - linters
  - lowercased
  - lookups
  - lts
  - makefile
  - maxconn
  - mexchanger
  - migrator
  - minimalistic
  - minsize
  - mixin
  - mkdir
  - multipartsearch
  - multiselect
  - mutex
  - mutexes
  - namespace
  - namespaces
  - oidc
  - omitempty
  - openapi
  - optim
  - packagetag
  - param
  - params
  - parallelize
  - passthrough
  - placholder
  - podman
  - pre
  - quic
  - rbac
  - readme
  - recursivity
  - recv
  - redispatch
  - redoc
  - reimplement
  - releaser
  - repo
  - repos
  - req
  - rsync
  - ruleset
  - rulesets
  - saml
  - sanitization
  - schemas
  - scrollbar
  - scss
  - searchselect
  - sni
  - spammy
  - ssl
  - sso
  - struct
  - subnet
  - subresource
  - subresources
  - sudo
  - symlinks
  - syslog
  - textarea
  - tcp
  - timeseries
  - tls
  - tooltip
  - tsconfig
  - typings
  - ubuntu
  - uniq
  - unix
  - unmarshalling
  - unsub
  - uri
  - url
  - userlist
  - userlists
  - utils
  - vfg
  - vite
  - vrrp
  - vue
  - waf
  - wafadvanced
  - workdir
  - yaml
  - async
  - rehaul
