---
linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 42
  cyclop:
    max-complexity: 42
  maligned:
    suggest-new: true
  dupl:
    threshold: 200
  goconst:
    min-len: 2
    min-occurrences: 3
  gci:
    prefix: github.com/haproxytech/client-native/v5

linters:
  enable-all: true
  disable:
    - golint # deprecated, replaced with revive
    - interfacer # deprecated
    - maligned # deprecated
    - wrapcheck
    - nlreturn
    - gomnd
    - goerr113
    - exhaustivestruct
    - wsl
    - whitespace
    - lll
    - scopelint
    - nestif
    - funlen
    - paralleltest
    - godot
    - varnamelen
    - ireturn
    - ifshort

    - thelper
    - wastedassign
    - goconst

    - gci
    - exhaustruct
    - nonamedreturns
    - forcetypeassert #tmp needs to be on

issues:
  exclude:
    # bugs of typecheck linter
    - "undeclared name: `shellquote`"
    - "github.com/kballard/go-shellquote\" imported but not used"
    - "github.com/haproxytech/config-parser/v4/types\" imported but not used"

run:
  skip-dirs:
    - test
  skip-files:
    - ".*_test\\.go$"
