---
linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 30
  maligned:
    suggest-new: true
  dupl:
    threshold: 200
  goconst:
    min-len: 2
    min-occurrences: 3
  gci:
    local-prefixes: github.com/haproxytech/client-native/v2

linters:
  enable-all: true
  disable:
    - wrapcheck
    - nlreturn
    - gomnd
    - goerr113
    - exhaustivestruct
    - wsl
    - whitespace
    - lll
    - scopelint
    - nestif
    - funlen
    - paralleltest
    - godot

    - goconst

run:
  skip-dirs:
    - test
  skip-files:
    - ".*_test\\.go$"
