---
linters-settings:
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 42
  cyclop:
    max-complexity: 42
  maligned:
    suggest-new: true
  dupl:
    threshold: 200
  goconst:
    min-len: 2
    min-occurrences: 3
  gci:
    prefix: github.com/haproxytech/client-native/v6

linters:
  enable-all: true
  disable:
    - mnd
    - err113
    - wsl
    - wrapcheck
    - godot
    - varnamelen
    - nlreturn
    - ireturn
    - interfacebloat
    - forcetypeassert
    - exhaustruct
    - dupword
    - nestif
    - lll
    - depguard
    - funlen
    - gci
    - goconst
    - recvcheck
    - tenv #deprecated

issues:
  exclude-files:
    - ".*_test\\.go$"
  exclude-dirs:
    - test
  exclude:
    - "unused-parameter: parameter 'comment' seems to be unused"
    - "unused-parameter: parameter 'parts' seems to be unused"
    - "unused-parameter: parameter 'parserType' seems to be unused"
