// Code generated by go generate; DO NOT EDIT.
/*
Copyright 2019 HAProxy Technologies

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package tests

import (
	"fmt"
	"strings"
	"testing"

	"github.com/haproxytech/client-native/v6/config-parser/parsers"
)

func TestLuaLoadPerThread(t *testing.T) {
	tests := map[string]bool{
		"lua-load-per-thread /etc/haproxy/lua/foo.lua": true,
		"lua-load-per-thread":                          false,
		"---":                                          false,
		"--- ---":                                      false,
	}
	parser := &parsers.LuaLoadPerThread{}
	for command, shouldPass := range tests {
		t.Run(command, func(t *testing.T) {
			line := strings.TrimSpace(command)
			lines := strings.SplitN(line, "\n", -1)
			var err error
			parser.Init()
			if len(lines) > 1 {
				for _, line = range lines {
					line = strings.TrimSpace(line)
					if err = ProcessLine(line, parser); err != nil {
						break
					}
				}
			} else {
				err = ProcessLine(line, parser)
			}
			if shouldPass {
				if err != nil {
					t.Error(err)
					return
				}
				result, err := parser.Result()
				if err != nil {
					t.Error(err)
					return
				}
				var returnLine string
				if result[0].Comment == "" {
					returnLine = result[0].Data
				} else {
					returnLine = fmt.Sprintf("%s # %s", result[0].Data, result[0].Comment)
				}
				if command != returnLine {
					t.Errorf("error: has [%s] expects [%s]", returnLine, command)
				}
			} else {
				if err == nil {
					t.Errorf("error: did not throw error for line [%s]", line)
				}
				_, parseErr := parser.Result()
				if parseErr == nil {
					t.Errorf("error: did not throw error on result for line [%s]", line)
				}
			}
		})
	}
}

func TestLuaLoadPerThreadMultiple(t *testing.T) {
	parser := &parsers.LuaLoadPerThread{}
	parser.Init()

	// Test multiple instances
	lines := []string{
		"lua-load-per-thread /etc/haproxy/lua/ja4.lua",
		"lua-load-per-thread /etc/haproxy/lua/ja4h.lua",
	}

	for _, line := range lines {
		err := ProcessLine(line, parser)
		if err != nil {
			t.Errorf("error parsing line [%s]: %v", line, err)
			return
		}
	}

	result, err := parser.Result()
	if err != nil {
		t.Errorf("error getting result: %v", err)
		return
	}

	if len(result) != 2 {
		t.Errorf("expected 2 results, got %d", len(result))
		return
	}

	if result[0].Data != "lua-load-per-thread /etc/haproxy/lua/ja4.lua" {
		t.Errorf("expected first result to be 'lua-load-per-thread /etc/haproxy/lua/ja4.lua', got '%s'", result[0].Data)
	}

	if result[1].Data != "lua-load-per-thread /etc/haproxy/lua/ja4h.lua" {
		t.Errorf("expected second result to be 'lua-load-per-thread /etc/haproxy/lua/ja4h.lua', got '%s'", result[1].Data)
	}
}
