# Copyright 2019 HAProxy Technologies LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG HAPROXY_VERSION=2.7
ARG DOCKER_URL=haproxytech
ARG GO_VERSION=1.19

FROM golang:${GO_VERSION}-alpine as go_image

FROM ${DOCKER_URL}/haproxy-alpine:${HAPROXY_VERSION}

RUN apk add --no-cache -U socat openssl util-linux htop tzdata bash gcc openssl wget git curl make bash jq && \
    rm -f /usr/local/bin/dataplaneapi /usr/bin/dataplaneapi && \
    rm -f /usr/local/etc/haproxy/haproxy.cfg && \
    chgrp -R haproxy /etc/haproxy /run /var &&\
    chmod -R g+w /etc/haproxy /run /var &&\
    mkdir -p /root/go
COPY --from=go_image /usr/local/go/ /usr/local/go/

ENV PATH=$PATH:/usr/local/go/bin \
    CGO_ENABLED=0 \
    PATH=$PATH:/usr/local/go/bin \
    HAPROXY_VERSION=$HAPROXY_VERSION

WORKDIR /src

ENTRYPOINT ["go"]
CMD ["test", "-tags", "integration", "./..."]
