name: go test
on: [push, pull_request]

jobs:
  e2e:
    name: e2e on HAProxy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        haproxyVersion: [2.1, 2.2, 2.3]
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Build
        uses: docker/build-push-action@v2
        with:
          file: ./e2e/Dockerfile
          build-args: |
            HAPROXY_VERSION=${{ matrix.haproxyVersion }}
          tags: client-native-test:${{ matrix.haproxyVersion }}
      - uses: addnab/docker-run-action@v2
        with:
          image: client-native-test:${{ matrix.haproxyVersion }}
          run: go test -tags integration ./...
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: |
        go test -v ./...
