// Code generated by go-method-gen. DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package models

import (
	"github.com/haproxytech/go-method-gen/pkg/eqdiff"
)

func (rec ConfigStickTable) Diff(obj ConfigStickTable, opts ...eqdiff.GoMethodGenOptions) map[string][]interface{} {
	diff := make(map[string][]interface{})
	for diffKey, diffValue := range DiffPointerInt64(rec.Expire, obj.Expire, opts...) {
		diff["Expire."+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.Keylen, obj.Keylen, opts...) {
		diff["Keylen."+diffKey] = diffValue
	}
	if rec.Nopurge != obj.Nopurge {
		diff["Nopurge"] = []interface{}{rec.Nopurge, obj.Nopurge}
	}
	if rec.Peers != obj.Peers {
		diff["Peers"] = []interface{}{rec.Peers, obj.Peers}
	}
	if rec.RecvOnly != obj.RecvOnly {
		diff["RecvOnly"] = []interface{}{rec.RecvOnly, obj.RecvOnly}
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.Size, obj.Size, opts...) {
		diff["Size."+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerString(rec.Srvkey, obj.Srvkey, opts...) {
		diff["Srvkey."+diffKey] = diffValue
	}
	if rec.Store != obj.Store {
		diff["Store"] = []interface{}{rec.Store, obj.Store}
	}
	if rec.Type != obj.Type {
		diff["Type"] = []interface{}{rec.Type, obj.Type}
	}
	for diffKey, diffValue := range DiffPointerString(rec.WriteTo, obj.WriteTo, opts...) {
		diff["WriteTo."+diffKey] = diffValue
	}
	return diff
}
