// Code generated by go-method-gen. DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package models

func (rec Defaults) Diff(obj Defaults) map[string][]interface{} {
	diff := make(map[string][]interface{})
	for diffKey, diffValue := range rec.DefaultsBase.Diff(obj.DefaultsBase) {
		diff["DefaultsBase."+diffKey] = diffValue
	}
	for diffKey, diffValue := range rec.ACLList.Diff(obj.ACLList) {
		diff["ACLList"+diffKey] = diffValue
	}
	for diffKey, diffValue := range rec.HTTPAfterResponseRuleList.Diff(obj.HTTPAfterResponseRuleList) {
		diff["HTTPAfterResponseRuleList"+diffKey] = diffValue
	}
	for diffKey, diffValue := range rec.HTTPCheckList.Diff(obj.HTTPCheckList) {
		diff["HTTPCheckList"+diffKey] = diffValue
	}
	for diffKey, diffValue := range rec.HTTPErrorRuleList.Diff(obj.HTTPErrorRuleList) {
		diff["HTTPErrorRuleList"+diffKey] = diffValue
	}
	for diffKey, diffValue := range rec.HTTPRequestRuleList.Diff(obj.HTTPRequestRuleList) {
		diff["HTTPRequestRuleList"+diffKey] = diffValue
	}
	for diffKey, diffValue := range rec.HTTPResponseRuleList.Diff(obj.HTTPResponseRuleList) {
		diff["HTTPResponseRuleList"+diffKey] = diffValue
	}
	for diffKey, diffValue := range rec.LogTargetList.Diff(obj.LogTargetList) {
		diff["LogTargetList"+diffKey] = diffValue
	}
	for diffKey, diffValue := range rec.QUICInitialRuleList.Diff(obj.QUICInitialRuleList) {
		diff["QUICInitialRuleList"+diffKey] = diffValue
	}
	for diffKey, diffValue := range rec.TCPCheckRuleList.Diff(obj.TCPCheckRuleList) {
		diff["TCPCheckRuleList"+diffKey] = diffValue
	}
	for diffKey, diffValue := range rec.TCPRequestRuleList.Diff(obj.TCPRequestRuleList) {
		diff["TCPRequestRuleList"+diffKey] = diffValue
	}
	for diffKey, diffValue := range rec.TCPResponseRuleList.Diff(obj.TCPResponseRuleList) {
		diff["TCPResponseRuleList"+diffKey] = diffValue
	}
	return diff
}
