// Code generated by go-method-gen. DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package models

import (
	"github.com/haproxytech/go-method-gen/pkg/eqdiff"
)

func (rec Defaults) Diff(obj Defaults, opts ...eqdiff.GoMethodGenOptions) map[string][]interface{} {
	diff := make(map[string][]interface{})
	for diffKey, diffValue := range rec.DefaultsBase.Diff(obj.DefaultsBase, opts...) {
		diff["DefaultsBase."+diffKey] = diffValue
	}
	for diffKey, diffValue := range rec.ACLList.Diff(obj.ACLList, opts...) {
		diff["ACLList"+diffKey] = diffValue
	}
	for diffKey, diffValue := range rec.HTTPAfterResponseRuleList.Diff(obj.HTTPAfterResponseRuleList, opts...) {
		diff["HTTPAfterResponseRuleList"+diffKey] = diffValue
	}
	for diffKey, diffValue := range rec.HTTPCheckList.Diff(obj.HTTPCheckList, opts...) {
		diff["HTTPCheckList"+diffKey] = diffValue
	}
	for diffKey, diffValue := range rec.HTTPErrorRuleList.Diff(obj.HTTPErrorRuleList, opts...) {
		diff["HTTPErrorRuleList"+diffKey] = diffValue
	}
	for diffKey, diffValue := range rec.HTTPRequestRuleList.Diff(obj.HTTPRequestRuleList, opts...) {
		diff["HTTPRequestRuleList"+diffKey] = diffValue
	}
	for diffKey, diffValue := range rec.HTTPResponseRuleList.Diff(obj.HTTPResponseRuleList, opts...) {
		diff["HTTPResponseRuleList"+diffKey] = diffValue
	}
	for diffKey, diffValue := range rec.LogTargetList.Diff(obj.LogTargetList, opts...) {
		diff["LogTargetList"+diffKey] = diffValue
	}
	for diffKey, diffValue := range rec.QUICInitialRuleList.Diff(obj.QUICInitialRuleList, opts...) {
		diff["QUICInitialRuleList"+diffKey] = diffValue
	}
	for diffKey, diffValue := range rec.TCPCheckRuleList.Diff(obj.TCPCheckRuleList, opts...) {
		diff["TCPCheckRuleList"+diffKey] = diffValue
	}
	for diffKey, diffValue := range rec.TCPRequestRuleList.Diff(obj.TCPRequestRuleList, opts...) {
		diff["TCPRequestRuleList"+diffKey] = diffValue
	}
	for diffKey, diffValue := range rec.TCPResponseRuleList.Diff(obj.TCPResponseRuleList, opts...) {
		diff["TCPResponseRuleList"+diffKey] = diffValue
	}
	return diff
}
