// Code generated by go-method-gen. DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package models

func (rec DgramBind) Diff(obj DgramBind) map[string][]interface{} {
	diff := make(map[string][]interface{})
	if rec.Address != obj.Address {
		diff["Address"] = []interface{}{rec.Address, obj.Address}
	}
	if rec.Interface != obj.Interface {
		diff["Interface"] = []interface{}{rec.Interface, obj.Interface}
	}
	if rec.Name != obj.Name {
		diff["Name"] = []interface{}{rec.Name, obj.Name}
	}
	if rec.Namespace != obj.Namespace {
		diff["Namespace"] = []interface{}{rec.Namespace, obj.Namespace}
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.Port, obj.Port) {
		diff["Port."+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.PortRangeEnd, obj.PortRangeEnd) {
		diff["PortRangeEnd."+diffKey] = diffValue
	}
	if rec.Transparent != obj.Transparent {
		diff["Transparent"] = []interface{}{rec.Transparent, obj.Transparent}
	}
	return diff
}
