// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// FilterSequence Filter Sequence
//
// Specifies in which order filters declared on the proxy should be executed
// for the request or response path. Corresponds to the HAProxy filter-sequence directive.
//
// swagger:model filter_sequence
type FilterSequence struct {
	// direction
	// Required: true
	// Enum: ["request","response"]
	// +kubebuilder:validation:Enum=request;response;
	Direction *string `json:"direction"`

	// filters
	// Required: true
	Filters []string `json:"filters"`

	// +kubebuilder:pruning:PreserveUnknownFields
	// +kubebuilder:validation:Schemaless
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// Validate validates this filter sequence
func (m *FilterSequence) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDirection(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFilters(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var filterSequenceTypeDirectionPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["request","response"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		filterSequenceTypeDirectionPropEnum = append(filterSequenceTypeDirectionPropEnum, v)
	}
}

const (

	// FilterSequenceDirectionRequest captures enum value "request"
	FilterSequenceDirectionRequest string = "request"

	// FilterSequenceDirectionResponse captures enum value "response"
	FilterSequenceDirectionResponse string = "response"
)

// prop value enum
func (m *FilterSequence) validateDirectionEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, filterSequenceTypeDirectionPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *FilterSequence) validateDirection(formats strfmt.Registry) error {

	if err := validate.Required("direction", "body", m.Direction); err != nil {
		return err
	}

	// value enum
	if err := m.validateDirectionEnum("direction", "body", *m.Direction); err != nil {
		return err
	}

	return nil
}

func (m *FilterSequence) validateFilters(formats strfmt.Registry) error {

	if err := validate.Required("filters", "body", m.Filters); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this filter sequence based on context it is used
func (m *FilterSequence) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FilterSequence) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FilterSequence) UnmarshalBinary(b []byte) error {
	var res FilterSequence
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
