// Code generated by go-method-gen. DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package models

func (rec HttpchkParams) Diff(obj HttpchkParams) map[string][]interface{} {
	diff := make(map[string][]interface{})
	if rec.Host != obj.Host {
		diff["Host"] = []interface{}{rec.Host, obj.Host}
	}
	if rec.Method != obj.Method {
		diff["Method"] = []interface{}{rec.Method, obj.Method}
	}
	if rec.URI != obj.URI {
		diff["URI"] = []interface{}{rec.URI, obj.URI}
	}
	if rec.Version != obj.Version {
		diff["Version"] = []interface{}{rec.Version, obj.Version}
	}
	return diff
}
