// Code generated by go-method-gen. DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package models

import (
	"github.com/haproxytech/go-method-gen/pkg/eqdiff"
)

func (rec HTTPResponseRule) Equal(obj HTTPResponseRule, opts ...eqdiff.GoMethodGenOptions) bool {
	return EqualSlicePointerReturnHeader(rec.ReturnHeaders, obj.ReturnHeaders, opts...) &&
		rec.ACLFile == obj.ACLFile &&
		rec.ACLKeyfmt == obj.ACLKeyfmt &&
		rec.BandwidthLimitLimit == obj.BandwidthLimitLimit &&
		rec.BandwidthLimitName == obj.BandwidthLimitName &&
		rec.BandwidthLimitPeriod == obj.BandwidthLimitPeriod &&
		rec.CacheName == obj.CacheName &&
		EqualPointerInt64(rec.CaptureID, obj.CaptureID, opts...) &&
		rec.CaptureSample == obj.CaptureSample &&
		rec.Cond == obj.Cond &&
		rec.CondTest == obj.CondTest &&
		EqualPointerInt64(rec.DenyStatus, obj.DenyStatus, opts...) &&
		rec.Expr == obj.Expr &&
		rec.HdrFormat == obj.HdrFormat &&
		rec.HdrMatch == obj.HdrMatch &&
		rec.HdrMethod == obj.HdrMethod &&
		rec.HdrName == obj.HdrName &&
		rec.LogLevel == obj.LogLevel &&
		rec.LuaAction == obj.LuaAction &&
		rec.LuaParams == obj.LuaParams &&
		rec.MapFile == obj.MapFile &&
		rec.MapKeyfmt == obj.MapKeyfmt &&
		rec.MapValuefmt == obj.MapValuefmt &&
		rec.MarkValue == obj.MarkValue &&
		EqualMapStringInterface(rec.Metadata, obj.Metadata, opts...) &&
		rec.NiceValue == obj.NiceValue &&
		EqualPointerInt64(rec.RedirCode, obj.RedirCode, opts...) &&
		rec.RedirOption == obj.RedirOption &&
		rec.RedirType == obj.RedirType &&
		rec.RedirValue == obj.RedirValue &&
		rec.ReturnContent == obj.ReturnContent &&
		rec.ReturnContentFormat == obj.ReturnContentFormat &&
		EqualPointerString(rec.ReturnContentType, obj.ReturnContentType, opts...) &&
		EqualPointerInt64(rec.ReturnStatusCode, obj.ReturnStatusCode, opts...) &&
		rec.RstTTL == obj.RstTTL &&
		rec.ScExpr == obj.ScExpr &&
		rec.ScID == obj.ScID &&
		rec.ScIdx == obj.ScIdx &&
		EqualPointerInt64(rec.ScInt, obj.ScInt, opts...) &&
		rec.SpoeEngine == obj.SpoeEngine &&
		rec.SpoeGroup == obj.SpoeGroup &&
		rec.Status == obj.Status &&
		rec.StatusReason == obj.StatusReason &&
		rec.StrictMode == obj.StrictMode &&
		rec.Timeout == obj.Timeout &&
		rec.TimeoutType == obj.TimeoutType &&
		rec.TosValue == obj.TosValue &&
		rec.TrackScKey == obj.TrackScKey &&
		EqualPointerInt64(rec.TrackScStickCounter, obj.TrackScStickCounter, opts...) &&
		rec.TrackScTable == obj.TrackScTable &&
		rec.Type == obj.Type &&
		rec.VarExpr == obj.VarExpr &&
		rec.VarFormat == obj.VarFormat &&
		rec.VarName == obj.VarName &&
		rec.VarScope == obj.VarScope &&
		EqualPointerInt64(rec.WaitAtLeast, obj.WaitAtLeast, opts...) &&
		EqualPointerInt64(rec.WaitTime, obj.WaitTime, opts...)
}
