// Code generated by go-method-gen. DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package models

import (
	"github.com/haproxytech/client-native/v6/models/funcs"
	"github.com/haproxytech/go-method-gen/pkg/eqdiff"
)

func (rec InfoAPI) Diff(obj InfoAPI, opts ...eqdiff.GoMethodGenOptions) map[string][]interface{} {
	diff := make(map[string][]interface{})
	for diffKey, diffValue := range funcs.DiffStrfmtDateTime(rec.BuildDate, obj.BuildDate, opts...) {
		diff["BuildDate."+diffKey] = diffValue
	}
	if rec.Version != obj.Version {
		diff["Version"] = []interface{}{rec.Version, obj.Version}
	}
	return diff
}
