// Code generated by go-method-gen. DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package models

import (
	"fmt"

	"github.com/haproxytech/go-method-gen/pkg/eqdiff"
)

func (rec LogForward) Diff(obj LogForward, opts ...eqdiff.GoMethodGenOptions) map[string][]interface{} {
	diff := make(map[string][]interface{})
	for diffKey, diffValue := range rec.LogForwardBase.Diff(obj.LogForwardBase, opts...) {
		diff["LogForwardBase."+diffKey] = diffValue
	}
	for diffKey, diffValue := range rec.LogTargetList.Diff(obj.LogTargetList, opts...) {
		diff["LogTargetList"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffMapStringBind(rec.Binds, obj.Binds, opts...) {
		diff["Binds"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffMapStringDgramBind(rec.DgramBinds, obj.DgramBinds, opts...) {
		diff["DgramBinds"+diffKey] = diffValue
	}
	return diff
}

func DiffMapStringDgramBind(x, y map[string]DgramBind, opts ...eqdiff.GoMethodGenOptions) map[string][]interface{} {
	diff := make(map[string][]interface{})
	if (x == nil && y == nil) || (len(x) == 0 && len(y) == 0) {
		return diff
	}

	var opt *eqdiff.GoMethodGenOptions
	if len(opts) > 0 {
		opt = &opts[0]
	}

	if opt == nil || (opt != nil && !opt.TreatNilNotAsEmpty) {
		if (x == nil && len(y) == 0) || (y == nil && len(x) == 0) {
			return diff
		}
	}

	if x == nil {
		return map[string][]interface{}{"": {nil, y}}
	}

	if y == nil {
		return map[string][]interface{}{"": {x, nil}}
	}

	for kx, vx := range x {
		key := fmt.Sprintf("[%v]", kx)
		vy := y[kx]

		for diffKey, diffValue := range vx.Diff(vy) {
			diff[key+"."+diffKey] = diffValue
		}

	}
	for ky, vy := range y {
		key := fmt.Sprintf("[%v]", ky)
		if _, found := diff[key]; found {
			continue
		}

		vx := x[ky]

		for diffKey, diffValue := range vx.Diff(vy) {
			diff[key+"."+diffKey] = []interface{}{diffValue[1], diffValue[0]}
		}

	}
	return diff
}
