// Code generated by go-method-gen. DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package models

func (rec MapEntry) Diff(obj MapEntry) map[string][]interface{} {
	diff := make(map[string][]interface{})
	if rec.ID != obj.ID {
		diff["ID"] = []interface{}{rec.ID, obj.ID}
	}
	if rec.Key != obj.Key {
		diff["Key"] = []interface{}{rec.Key, obj.Key}
	}
	if rec.Value != obj.Value {
		diff["Value"] = []interface{}{rec.Value, obj.Value}
	}
	return diff
}
