// Code generated by go-method-gen. DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package models

import (
	"github.com/haproxytech/client-native/v6/models/funcs"
	"github.com/haproxytech/go-method-gen/pkg/eqdiff"
)

func (rec ProcessInfoItem) Diff(obj ProcessInfoItem, opts ...eqdiff.GoMethodGenOptions) map[string][]interface{} {
	diff := make(map[string][]interface{})
	for diffKey, diffValue := range DiffPointerInt64(rec.ActivePeers, obj.ActivePeers, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["ActivePeers"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.BusyPolling, obj.BusyPolling, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["BusyPolling"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.BytesOutRate, obj.BytesOutRate, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["BytesOutRate"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.CompressBpsIn, obj.CompressBpsIn, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["CompressBpsIn"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.CompressBpsOut, obj.CompressBpsOut, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["CompressBpsOut"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.CompressBpsRateLim, obj.CompressBpsRateLim, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["CompressBpsRateLim"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.ConnRate, obj.ConnRate, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["ConnRate"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.ConnRateLimit, obj.ConnRateLimit, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["ConnRateLimit"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.ConnectedPeers, obj.ConnectedPeers, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["ConnectedPeers"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.CumConns, obj.CumConns, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["CumConns"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.CumReq, obj.CumReq, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["CumReq"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.CumSslConns, obj.CumSslConns, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["CumSslConns"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.CurrConns, obj.CurrConns, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["CurrConns"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.CurrSslConns, obj.CurrSslConns, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["CurrSslConns"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.DroppedLogs, obj.DroppedLogs, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["DroppedLogs"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.FailedResolutions, obj.FailedResolutions, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["FailedResolutions"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.HardMaxConn, obj.HardMaxConn, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["HardMaxConn"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.IdlePct, obj.IdlePct, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["IdlePct"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.Jobs, obj.Jobs, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["Jobs"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.Listeners, obj.Listeners, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["Listeners"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.MaxConn, obj.MaxConn, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["MaxConn"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.MaxConnRate, obj.MaxConnRate, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["MaxConnRate"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.MaxPipes, obj.MaxPipes, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["MaxPipes"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.MaxSessRate, obj.MaxSessRate, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["MaxSessRate"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.MaxSock, obj.MaxSock, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["MaxSock"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.MaxSslConns, obj.MaxSslConns, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["MaxSslConns"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.MaxSslRate, obj.MaxSslRate, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["MaxSslRate"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.MaxZlibMemUsage, obj.MaxZlibMemUsage, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["MaxZlibMemUsage"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.MemMaxMb, obj.MemMaxMb, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["MemMaxMb"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.Nbthread, obj.Nbthread, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["Nbthread"+diffKey] = diffValue
	}
	if rec.Node != obj.Node {
		diff["Node"] = []interface{}{rec.Node, obj.Node}
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.Pid, obj.Pid, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["Pid"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.PipesFree, obj.PipesFree, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["PipesFree"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.PipesUsed, obj.PipesUsed, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["PipesUsed"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.PoolAllocMb, obj.PoolAllocMb, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["PoolAllocMb"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.PoolFailed, obj.PoolFailed, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["PoolFailed"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.PoolUsedMb, obj.PoolUsedMb, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["PoolUsedMb"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.ProcessNum, obj.ProcessNum, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["ProcessNum"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.Processes, obj.Processes, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["Processes"+diffKey] = diffValue
	}
	for diffKey, diffValue := range funcs.DiffStrfmtDate(rec.ReleaseDate, obj.ReleaseDate, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["ReleaseDate"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.RunQueue, obj.RunQueue, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["RunQueue"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.SessRate, obj.SessRate, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["SessRate"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.SessRateLimit, obj.SessRateLimit, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["SessRateLimit"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.SslBackendKeyRate, obj.SslBackendKeyRate, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["SslBackendKeyRate"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.SslBackendMaxKeyRate, obj.SslBackendMaxKeyRate, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["SslBackendMaxKeyRate"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.SslCacheLookups, obj.SslCacheLookups, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["SslCacheLookups"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.SslCacheMisses, obj.SslCacheMisses, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["SslCacheMisses"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.SslFrontendKeyRate, obj.SslFrontendKeyRate, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["SslFrontendKeyRate"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.SslFrontendMaxKeyRate, obj.SslFrontendMaxKeyRate, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["SslFrontendMaxKeyRate"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.SslFrontendSessionReuse, obj.SslFrontendSessionReuse, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["SslFrontendSessionReuse"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.SslRate, obj.SslRate, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["SslRate"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.SslRateLimit, obj.SslRateLimit, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["SslRateLimit"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.Stopping, obj.Stopping, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["Stopping"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.Tasks, obj.Tasks, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["Tasks"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.TotalBytesOut, obj.TotalBytesOut, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["TotalBytesOut"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.Ulimitn, obj.Ulimitn, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["Ulimitn"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.Unstoppable, obj.Unstoppable, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["Unstoppable"+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.Uptime, obj.Uptime, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["Uptime"+diffKey] = diffValue
	}
	if rec.Version != obj.Version {
		diff["Version"] = []interface{}{rec.Version, obj.Version}
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.ZlibMemUsage, obj.ZlibMemUsage, opts...) {
		if diffKey != "" && diffKey[0] != '.' && diffKey[0] != '[' {
			diffKey = "." + diffKey
		}
		diff["ZlibMemUsage"+diffKey] = diffValue
	}
	return diff
}
