// Code generated by go-method-gen. DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package models

import (
	"github.com/haproxytech/go-method-gen/pkg/eqdiff"
)

func (rec ProcessInfoItem) Equal(obj ProcessInfoItem, opts ...eqdiff.GoMethodGenOptions) bool {
	return EqualPointerInt64(rec.ActivePeers, obj.ActivePeers, opts...) &&
		EqualPointerInt64(rec.BusyPolling, obj.BusyPolling, opts...) &&
		EqualPointerInt64(rec.BytesOutRate, obj.BytesOutRate, opts...) &&
		EqualPointerInt64(rec.CompressBpsIn, obj.CompressBpsIn, opts...) &&
		EqualPointerInt64(rec.CompressBpsOut, obj.CompressBpsOut, opts...) &&
		EqualPointerInt64(rec.CompressBpsRateLim, obj.CompressBpsRateLim, opts...) &&
		EqualPointerInt64(rec.ConnRate, obj.ConnRate, opts...) &&
		EqualPointerInt64(rec.ConnRateLimit, obj.ConnRateLimit, opts...) &&
		EqualPointerInt64(rec.ConnectedPeers, obj.ConnectedPeers, opts...) &&
		EqualPointerInt64(rec.CumConns, obj.CumConns, opts...) &&
		EqualPointerInt64(rec.CumReq, obj.CumReq, opts...) &&
		EqualPointerInt64(rec.CumSslConns, obj.CumSslConns, opts...) &&
		EqualPointerInt64(rec.CurrConns, obj.CurrConns, opts...) &&
		EqualPointerInt64(rec.CurrSslConns, obj.CurrSslConns, opts...) &&
		EqualPointerInt64(rec.DroppedLogs, obj.DroppedLogs, opts...) &&
		EqualPointerInt64(rec.FailedResolutions, obj.FailedResolutions, opts...) &&
		EqualPointerInt64(rec.HardMaxConn, obj.HardMaxConn, opts...) &&
		EqualPointerInt64(rec.IdlePct, obj.IdlePct, opts...) &&
		EqualPointerInt64(rec.Jobs, obj.Jobs, opts...) &&
		EqualPointerInt64(rec.Listeners, obj.Listeners, opts...) &&
		EqualPointerInt64(rec.MaxConn, obj.MaxConn, opts...) &&
		EqualPointerInt64(rec.MaxConnRate, obj.MaxConnRate, opts...) &&
		EqualPointerInt64(rec.MaxPipes, obj.MaxPipes, opts...) &&
		EqualPointerInt64(rec.MaxSessRate, obj.MaxSessRate, opts...) &&
		EqualPointerInt64(rec.MaxSock, obj.MaxSock, opts...) &&
		EqualPointerInt64(rec.MaxSslConns, obj.MaxSslConns, opts...) &&
		EqualPointerInt64(rec.MaxSslRate, obj.MaxSslRate, opts...) &&
		EqualPointerInt64(rec.MaxZlibMemUsage, obj.MaxZlibMemUsage, opts...) &&
		EqualPointerInt64(rec.MemMaxMb, obj.MemMaxMb, opts...) &&
		EqualPointerInt64(rec.Nbthread, obj.Nbthread, opts...) &&
		rec.Node == obj.Node &&
		EqualPointerInt64(rec.Pid, obj.Pid, opts...) &&
		EqualPointerInt64(rec.PipesFree, obj.PipesFree, opts...) &&
		EqualPointerInt64(rec.PipesUsed, obj.PipesUsed, opts...) &&
		EqualPointerInt64(rec.PoolAllocMb, obj.PoolAllocMb, opts...) &&
		EqualPointerInt64(rec.PoolFailed, obj.PoolFailed, opts...) &&
		EqualPointerInt64(rec.PoolUsedMb, obj.PoolUsedMb, opts...) &&
		EqualPointerInt64(rec.ProcessNum, obj.ProcessNum, opts...) &&
		EqualPointerInt64(rec.Processes, obj.Processes, opts...) &&
		rec.ReleaseDate.Equal(obj.ReleaseDate) &&
		EqualPointerInt64(rec.RunQueue, obj.RunQueue, opts...) &&
		EqualPointerInt64(rec.SessRate, obj.SessRate, opts...) &&
		EqualPointerInt64(rec.SessRateLimit, obj.SessRateLimit, opts...) &&
		EqualPointerInt64(rec.SslBackendKeyRate, obj.SslBackendKeyRate, opts...) &&
		EqualPointerInt64(rec.SslBackendMaxKeyRate, obj.SslBackendMaxKeyRate, opts...) &&
		EqualPointerInt64(rec.SslCacheLookups, obj.SslCacheLookups, opts...) &&
		EqualPointerInt64(rec.SslCacheMisses, obj.SslCacheMisses, opts...) &&
		EqualPointerInt64(rec.SslFrontendKeyRate, obj.SslFrontendKeyRate, opts...) &&
		EqualPointerInt64(rec.SslFrontendMaxKeyRate, obj.SslFrontendMaxKeyRate, opts...) &&
		EqualPointerInt64(rec.SslFrontendSessionReuse, obj.SslFrontendSessionReuse, opts...) &&
		EqualPointerInt64(rec.SslRate, obj.SslRate, opts...) &&
		EqualPointerInt64(rec.SslRateLimit, obj.SslRateLimit, opts...) &&
		EqualPointerInt64(rec.Stopping, obj.Stopping, opts...) &&
		EqualPointerInt64(rec.Tasks, obj.Tasks, opts...) &&
		EqualPointerInt64(rec.TotalBytesOut, obj.TotalBytesOut, opts...) &&
		EqualPointerInt64(rec.Ulimitn, obj.Ulimitn, opts...) &&
		EqualPointerInt64(rec.Unstoppable, obj.Unstoppable, opts...) &&
		EqualPointerInt64(rec.Uptime, obj.Uptime, opts...) &&
		rec.Version == obj.Version &&
		EqualPointerInt64(rec.ZlibMemUsage, obj.ZlibMemUsage, opts...)
}
