// Code generated by go-method-gen. DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package models

func (rec Program) Diff(obj Program) map[string][]interface{} {
	diff := make(map[string][]interface{})
	for diffKey, diffValue := range DiffPointerString(rec.Command, obj.Command) {
		diff["Command."+diffKey] = diffValue
	}
	if rec.Group != obj.Group {
		diff["Group"] = []interface{}{rec.Group, obj.Group}
	}
	if rec.Name != obj.Name {
		diff["Name"] = []interface{}{rec.Name, obj.Name}
	}
	if rec.StartOnReload != obj.StartOnReload {
		diff["StartOnReload"] = []interface{}{rec.StartOnReload, obj.StartOnReload}
	}
	if rec.User != obj.User {
		diff["User"] = []interface{}{rec.User, obj.User}
	}
	return diff
}
