// Code generated by go-method-gen. DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package models

func (rec RingBase) Equal(obj RingBase) bool {
	return rec.Description == obj.Description &&
		rec.Format == obj.Format &&
		EqualPointerInt64(rec.Maxlen, obj.Maxlen) &&
		rec.Name == obj.Name &&
		EqualPointerInt64(rec.Size, obj.Size) &&
		EqualPointerInt64(rec.TimeoutConnect, obj.TimeoutConnect) &&
		EqualPointerInt64(rec.TimeoutServer, obj.TimeoutServer)
}
