// Code generated by go-method-gen. DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package models

import (
	"github.com/haproxytech/go-method-gen/pkg/eqdiff"
)

func (rec RuntimeServer) Diff(obj RuntimeServer, opts ...eqdiff.GoMethodGenOptions) map[string][]interface{} {
	diff := make(map[string][]interface{})
	if rec.Address != obj.Address {
		diff["Address"] = []interface{}{rec.Address, obj.Address}
	}
	if rec.AdminState != obj.AdminState {
		diff["AdminState"] = []interface{}{rec.AdminState, obj.AdminState}
	}
	if rec.AgentAddr != obj.AgentAddr {
		diff["AgentAddr"] = []interface{}{rec.AgentAddr, obj.AgentAddr}
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.AgentPort, obj.AgentPort, opts...) {
		diff["AgentPort."+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.AgentState, obj.AgentState, opts...) {
		diff["AgentState."+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.BackendForcedID, obj.BackendForcedID, opts...) {
		diff["BackendForcedID."+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.BackendID, obj.BackendID, opts...) {
		diff["BackendID."+diffKey] = diffValue
	}
	if rec.BackendName != obj.BackendName {
		diff["BackendName"] = []interface{}{rec.BackendName, obj.BackendName}
	}
	if rec.CheckAddr != obj.CheckAddr {
		diff["CheckAddr"] = []interface{}{rec.CheckAddr, obj.CheckAddr}
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.CheckHealth, obj.CheckHealth, opts...) {
		diff["CheckHealth."+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.CheckPort, obj.CheckPort, opts...) {
		diff["CheckPort."+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.CheckResult, obj.CheckResult, opts...) {
		diff["CheckResult."+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.CheckState, obj.CheckState, opts...) {
		diff["CheckState."+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.CheckStatus, obj.CheckStatus, opts...) {
		diff["CheckStatus."+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.ForecedID, obj.ForecedID, opts...) {
		diff["ForecedID."+diffKey] = diffValue
	}
	if rec.Fqdn != obj.Fqdn {
		diff["Fqdn"] = []interface{}{rec.Fqdn, obj.Fqdn}
	}
	if rec.ID != obj.ID {
		diff["ID"] = []interface{}{rec.ID, obj.ID}
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.Iweight, obj.Iweight, opts...) {
		diff["Iweight."+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.LastTimeChange, obj.LastTimeChange, opts...) {
		diff["LastTimeChange."+diffKey] = diffValue
	}
	if rec.Name != obj.Name {
		diff["Name"] = []interface{}{rec.Name, obj.Name}
	}
	if rec.OperationalState != obj.OperationalState {
		diff["OperationalState"] = []interface{}{rec.OperationalState, obj.OperationalState}
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.Port, obj.Port, opts...) {
		diff["Port."+diffKey] = diffValue
	}
	if rec.Srvrecord != obj.Srvrecord {
		diff["Srvrecord"] = []interface{}{rec.Srvrecord, obj.Srvrecord}
	}
	for diffKey, diffValue := range DiffPointerBool(rec.UseSsl, obj.UseSsl, opts...) {
		diff["UseSsl."+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.Uweight, obj.Uweight, opts...) {
		diff["Uweight."+diffKey] = diffValue
	}
	return diff
}
