// Code generated by go-method-gen. DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package models

func (rec ServerTemplate) Diff(obj ServerTemplate) map[string][]interface{} {
	diff := make(map[string][]interface{})
	for diffKey, diffValue := range rec.ServerParams.Diff(obj.ServerParams) {
		diff["ServerParams."+diffKey] = diffValue
	}
	if rec.Fqdn != obj.Fqdn {
		diff["Fqdn"] = []interface{}{rec.Fqdn, obj.Fqdn}
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.ID, obj.ID) {
		diff["ID."+diffKey] = diffValue
	}
	if rec.NumOrRange != obj.NumOrRange {
		diff["NumOrRange"] = []interface{}{rec.NumOrRange, obj.NumOrRange}
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.Port, obj.Port) {
		diff["Port."+diffKey] = diffValue
	}
	if rec.Prefix != obj.Prefix {
		diff["Prefix"] = []interface{}{rec.Prefix, obj.Prefix}
	}
	return diff
}
