// Code generated by go-method-gen. DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package models

func (x SpoeAgents) Equal(y SpoeAgents) bool {
	return EqualSpoeAgents(x, y)
}

func EqualPointerSpoeAgent(x, y *SpoeAgent) bool {
	if x == nil || y == nil {
		return x == y
	}
	return (*x).Equal(*y)
}

func EqualSpoeAgents(x, y SpoeAgents) bool {
	if len(x) != len(y) {
		return false
	}

	for i, vx := range x {
		vy := y[i]
		if !EqualPointerSpoeAgent(vx, vy) {
			return false
		}
	}

	return true
}
