// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SslCertificateID SSL Certificate ID
//
// # SSL Certificate ID
//
// swagger:model ssl_certificate_id
type SslCertificateID struct {

	// certificate id
	CertificateID *CertificateID `json:"certificate_id,omitempty"`

	// certificate id key
	CertificateIDKey string `json:"certificate_id_key,omitempty"`

	// certificate path
	CertificatePath string `json:"certificate_path,omitempty"`
}

// Validate validates this ssl certificate id
func (m *SslCertificateID) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCertificateID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SslCertificateID) validateCertificateID(formats strfmt.Registry) error {
	if swag.IsZero(m.CertificateID) { // not required
		return nil
	}

	if m.CertificateID != nil {
		if err := m.CertificateID.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("certificate_id")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("certificate_id")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this ssl certificate id based on the context it is used
func (m *SslCertificateID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCertificateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SslCertificateID) contextValidateCertificateID(ctx context.Context, formats strfmt.Registry) error {

	if m.CertificateID != nil {
		if err := m.CertificateID.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("certificate_id")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("certificate_id")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SslCertificateID) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SslCertificateID) UnmarshalBinary(b []byte) error {
	var res SslCertificateID
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
