// Code generated by go-method-gen. DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package models

func (rec SSLFrontUse) Equal(obj SSLFrontUse) bool {
	return rec.Allow0rtt == obj.Allow0rtt &&
		rec.Alpn == obj.Alpn &&
		rec.CaFile == obj.CaFile &&
		rec.Certificate == obj.Certificate &&
		rec.Ciphers == obj.Ciphers &&
		rec.Ciphersuites == obj.Ciphersuites &&
		rec.ClientSigalgs == obj.ClientSigalgs &&
		rec.CrlFile == obj.CrlFile &&
		rec.Curves == obj.Curves &&
		rec.Ecdhe == obj.Ecdhe &&
		rec.Issuer == obj.Issuer &&
		rec.Key == obj.Key &&
		rec.NoAlpn == obj.NoAlpn &&
		rec.NoCaNames == obj.NoCaNames &&
		rec.Npn == obj.Npn &&
		rec.Ocsp == obj.Ocsp &&
		rec.OcspUpdate == obj.OcspUpdate &&
		rec.Sctl == obj.Sctl &&
		rec.Sigalgs == obj.Sigalgs &&
		rec.SslMaxVer == obj.SslMaxVer &&
		rec.SslMinVer == obj.SslMinVer &&
		rec.Verify == obj.Verify
}
