// Code generated by go-method-gen. DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package models

import (
	"github.com/haproxytech/client-native/v6/models/funcs"
	"github.com/haproxytech/go-method-gen/pkg/eqdiff"
)

func (rec SslOcspResponse) Diff(obj SslOcspResponse, opts ...eqdiff.GoMethodGenOptions) map[string][]interface{} {
	diff := make(map[string][]interface{})
	if rec.Base64Response != obj.Base64Response {
		diff["Base64Response"] = []interface{}{rec.Base64Response, obj.Base64Response}
	}
	if rec.OcspResponseStatus != obj.OcspResponseStatus {
		diff["OcspResponseStatus"] = []interface{}{rec.OcspResponseStatus, obj.OcspResponseStatus}
	}
	for diffKey, diffValue := range funcs.DiffStrfmtDate(rec.ProducedAt, obj.ProducedAt, opts...) {
		diff["ProducedAt."+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffSliceString(rec.ResponderID, obj.ResponderID, opts...) {
		diff["ResponderID"+diffKey] = diffValue
	}
	if rec.ResponseType != obj.ResponseType {
		diff["ResponseType"] = []interface{}{rec.ResponseType, obj.ResponseType}
	}
	for diffKey, diffValue := range DiffPointerOCSPResponses(rec.Responses, obj.Responses, opts...) {
		diff["Responses."+diffKey] = diffValue
	}
	if rec.Version != obj.Version {
		diff["Version"] = []interface{}{rec.Version, obj.Version}
	}
	return diff
}

func DiffPointerOCSPResponses(x, y *OCSPResponses, opts ...eqdiff.GoMethodGenOptions) map[string][]interface{} {
	diff := make(map[string][]interface{})
	if x == nil && y == nil {
		return diff
	}

	key := "Responses"

	switch {
	case x == nil:
		diff[key] = []interface{}{x, *y}
		return diff
	case y == nil:
		diff[key] = []interface{}{*x, y}
		return diff
	}

	for diffKey, diffValue := range (*x).Diff(*y) {
		diff[key+"."+diffKey] = diffValue
	}

	return diff
}
