// Code generated by go-method-gen. DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package models

func (rec Table) Diff(obj Table) map[string][]interface{} {
	diff := make(map[string][]interface{})
	for diffKey, diffValue := range DiffPointerString(rec.Expire, obj.Expire) {
		diff["Expire."+diffKey] = diffValue
	}
	if rec.Name != obj.Name {
		diff["Name"] = []interface{}{rec.Name, obj.Name}
	}
	if rec.NoPurge != obj.NoPurge {
		diff["NoPurge"] = []interface{}{rec.NoPurge, obj.NoPurge}
	}
	if rec.RecvOnly != obj.RecvOnly {
		diff["RecvOnly"] = []interface{}{rec.RecvOnly, obj.RecvOnly}
	}
	if rec.Size != obj.Size {
		diff["Size"] = []interface{}{rec.Size, obj.Size}
	}
	if rec.Store != obj.Store {
		diff["Store"] = []interface{}{rec.Store, obj.Store}
	}
	if rec.Type != obj.Type {
		diff["Type"] = []interface{}{rec.Type, obj.Type}
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.TypeLen, obj.TypeLen) {
		diff["TypeLen."+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerString(rec.WriteTo, obj.WriteTo) {
		diff["WriteTo."+diffKey] = diffValue
	}
	return diff
}
