// Code generated by go-method-gen. DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package models

func (rec TCPResponseRule) Equal(obj TCPResponseRule) bool {
	return rec.Action == obj.Action &&
		rec.BandwidthLimitLimit == obj.BandwidthLimitLimit &&
		rec.BandwidthLimitName == obj.BandwidthLimitName &&
		rec.BandwidthLimitPeriod == obj.BandwidthLimitPeriod &&
		rec.Cond == obj.Cond &&
		rec.CondTest == obj.CondTest &&
		rec.Expr == obj.Expr &&
		rec.LogLevel == obj.LogLevel &&
		rec.LuaAction == obj.LuaAction &&
		rec.LuaParams == obj.LuaParams &&
		rec.MarkValue == obj.MarkValue &&
		rec.NiceValue == obj.NiceValue &&
		rec.RstTTL == obj.RstTTL &&
		rec.ScExpr == obj.ScExpr &&
		rec.ScID == obj.ScID &&
		rec.ScIdx == obj.ScIdx &&
		EqualPointerInt64(rec.ScInt, obj.ScInt) &&
		rec.SpoeEngine == obj.SpoeEngine &&
		rec.SpoeGroup == obj.SpoeGroup &&
		EqualPointerInt64(rec.Timeout, obj.Timeout) &&
		rec.TosValue == obj.TosValue &&
		rec.Type == obj.Type &&
		rec.VarFormat == obj.VarFormat &&
		rec.VarName == obj.VarName &&
		rec.VarScope == obj.VarScope
}
