// Code generated by go-method-gen. DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package models

import (
	"github.com/haproxytech/go-method-gen/pkg/eqdiff"
)

func (rec TuneQuicOptions) Diff(obj TuneQuicOptions, opts ...eqdiff.GoMethodGenOptions) map[string][]interface{} {
	diff := make(map[string][]interface{})
	for diffKey, diffValue := range DiffPointerInt64(rec.FrontendConnTxBuffersLimit, obj.FrontendConnTxBuffersLimit, opts...) {
		diff["FrontendConnTxBuffersLimit."+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.FrontendMaxIdleTimeout, obj.FrontendMaxIdleTimeout, opts...) {
		diff["FrontendMaxIdleTimeout."+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.FrontendMaxStreamsBidi, obj.FrontendMaxStreamsBidi, opts...) {
		diff["FrontendMaxStreamsBidi."+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.FrontendMaxTxMemory, obj.FrontendMaxTxMemory, opts...) {
		diff["FrontendMaxTxMemory."+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.MaxFrameLoss, obj.MaxFrameLoss, opts...) {
		diff["MaxFrameLoss."+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.ReorderRatio, obj.ReorderRatio, opts...) {
		diff["ReorderRatio."+diffKey] = diffValue
	}
	for diffKey, diffValue := range DiffPointerInt64(rec.RetryThreshold, obj.RetryThreshold, opts...) {
		diff["RetryThreshold."+diffKey] = diffValue
	}
	if rec.SocketOwner != obj.SocketOwner {
		diff["SocketOwner"] = []interface{}{rec.SocketOwner, obj.SocketOwner}
	}
	if rec.ZeroCopyFwdSend != obj.ZeroCopyFwdSend {
		diff["ZeroCopyFwdSend"] = []interface{}{rec.ZeroCopyFwdSend, obj.ZeroCopyFwdSend}
	}
	return diff
}
