// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UseSmallBuffers Enables support for small buffers for the given categories.
//
// swagger:model use_small_buffers
type UseSmallBuffers struct {

	// check
	Check bool `json:"check,omitempty"`

	// enabled
	// Required: true
	// Enum: ["enabled","disabled"]
	// +kubebuilder:validation:Enum=enabled;disabled;
	Enabled *string `json:"enabled"`

	// l7 retries
	L7Retries bool `json:"l7_retries,omitempty"`

	// queue
	Queue bool `json:"queue,omitempty"`
}

// Validate validates this use small buffers
func (m *UseSmallBuffers) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEnabled(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var useSmallBuffersTypeEnabledPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["enabled","disabled"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		useSmallBuffersTypeEnabledPropEnum = append(useSmallBuffersTypeEnabledPropEnum, v)
	}
}

const (

	// UseSmallBuffersEnabledEnabled captures enum value "enabled"
	UseSmallBuffersEnabledEnabled string = "enabled"

	// UseSmallBuffersEnabledDisabled captures enum value "disabled"
	UseSmallBuffersEnabledDisabled string = "disabled"
)

// prop value enum
func (m *UseSmallBuffers) validateEnabledEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, useSmallBuffersTypeEnabledPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *UseSmallBuffers) validateEnabled(formats strfmt.Registry) error {

	if err := validate.Required("enabled", "body", m.Enabled); err != nil {
		return err
	}

	// value enum
	if err := m.validateEnabledEnum("enabled", "body", *m.Enabled); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this use small buffers based on context it is used
func (m *UseSmallBuffers) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UseSmallBuffers) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UseSmallBuffers) UnmarshalBinary(b []byte) error {
	var res UseSmallBuffers
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
